Repository EncryFoundation/EncryCore, pull requests merged in 2018-06, with the labels that each got.

#64 Miner worker refactoring#ec-226
  src/main/scala/encry/cli/commands/StartMine.scala
  src/main/scala/encry/cli/commands/StopMine.scala
  src/main/scala/encry/local/miner/EncryMiner.scala
  src/main/scala/encry/local/miner/EncryMiningWorker.scala
Labels: review required

#73 ec-241-Disable EncryScanner
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/account/Portfolio.scala
  src/main/scala/encry/api/http/routes/StateInfoApiRoute.scala
  src/main/scala/encry/local/scanner/EncryScanner.scala
  src/main/scala/encry/local/scanner/storage/EncryIndexReader.scala
  src/main/scala/encry/local/scanner/storage/IndexStorage.scala
Labels: review required

#75 ec-240 strange input
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
Labels: review required

#74 ec-243 Fix warning NTP at start of an app
  src/main/scala/encry/utils/NetworkTime.scala
Labels: review required

#78 Incorrect start of miner fix#EC-239
  src/main/scala/encry/EncryApp.scala
Labels: bug, review required

#70 Ec-233 Fix configs and constants
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/consensus/DifficultySerializer.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/Handshake.scala
  src/main/scala/encry/network/NetworkController.scala
  src/main/scala/encry/network/PeerConnectionHandler.scala
  src/main/scala/encry/network/message/BasicMessagesRepo.scala
  src/main/scala/encry/network/message/Message.scala
  src/main/scala/encry/settings/Constants.scala
  src/main/scala/encry/settings/EncryAppSettings.scala
  src/main/scala/encry/settings/NetworkSettings.scala
  src/main/scala/encry/settings/WalletSettings.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
Labels: done

#82 ec-246: Make separated dispatcher for actor and/or workers
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/local/miner/EncryMiner.scala
  src/main/scala/encry/local/miner/EncryMiningWorker.scala
Labels: review required

#81 Base58 -> Algos
  src/main/scala/encry/api/http/UtilsApiRoute.scala
  src/main/scala/encry/api/http/routes/EncryBaseApiRoute.scala
  src/main/scala/encry/api/http/routes/HistoryApiRoute.scala
  src/main/scala/encry/api/http/routes/InfoApiRoute.scala
  src/main/scala/encry/consensus/History.scala
  src/main/scala/encry/encryCore.scala
  src/main/scala/encry/modifiers/NodeViewModifier.scala
  src/main/scala/encry/modifiers/history/ADProofs.scala
  src/main/scala/encry/modifiers/history/block/payload/EncryBlockPayload.scala
  src/main/scala/encry/modifiers/mempool/directive/AssetIssuingDirective.scala
  src/main/scala/encry/modifiers/mempool/directive/DataDirective.scala
  src/main/scala/encry/modifiers/mempool/directive/ScriptedAssetDirective.scala
  src/main/scala/encry/modifiers/state/box/EncryProposition.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/validation/ModifierValidation.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/state/Signature25519.scala
  src/main/scala/scorex/crypto/authds/avltree/batch/VersionedIODBAVLStorage.scala
Labels: masterpiece

#80 Wallet redisign#ec 242
  src/main/scala/encry/view/wallet/EncryWallet.scala
  src/main/scala/encry/view/wallet/storage/WalletStorage.scala
  src/test/scala/encry/utils/EncryGenerator.scala
  src/test/scala/encry/view/wallet/WalletSpec.scala
Labels: review required
