Repository EncryFoundation/EncryCore, pull requests merged in 2018-09, with the labels that each got.

#174 ec-zombie
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/api/http/routes/EncryBaseApiRoute.scala
  src/main/scala/encry/api/http/routes/HistoryApiRoute.scala
  src/main/scala/encry/cli/ConsoleListener.scala
  src/main/scala/encry/consensus/ConsensusScheme.scala
  src/main/scala/encry/consensus/EquihashPowScheme.scala
  src/main/scala/encry/consensus/History.scala
  src/main/scala/encry/local/TransactionGenerator.scala
  src/main/scala/encry/local/explorer/BlockListener.scala
  src/main/scala/encry/local/explorer/database/DBService.scala
  src/main/scala/encry/local/explorer/database/QueryRepository.scala
  src/main/scala/encry/modifiers/EncryPersistentModifier.scala
  src/main/scala/encry/modifiers/ModifierWithDigest.scala
  src/main/scala/encry/modifiers/NodeViewModifier.scala
  src/main/scala/encry/modifiers/history/ADProofs.scala
  src/main/scala/encry/modifiers/history/block/EncryBlock.scala
  src/main/scala/encry/modifiers/history/block/header/EncryBaseBlockHeader.scala
  src/main/scala/encry/modifiers/history/block/header/EncryBlockHeader.scala
  src/main/scala/encry/modifiers/history/block/payload/EncryBaseBlockPayload.scala
  src/main/scala/encry/modifiers/history/block/payload/EncryBlockPayload.scala
  src/main/scala/encry/modifiers/mempool/EncryTransaction.scala
  src/main/scala/encry/modifiers/mempool/Transaction.scala
  src/main/scala/encry/network/DeliveryManager.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/network/PeerConnectionHandler.scala
  src/main/scala/encry/network/PeerSynchronizer.scala
  src/main/scala/encry/network/message/BasicMessagesRepo.scala
  src/main/scala/encry/stats/StatsSender.scala
  src/main/scala/encry/stats/Zombie.scala
  src/main/scala/encry/storage/EncryStorage.scala
  src/main/scala/encry/utils/Cancellable.scala
  src/main/scala/encry/utils/CoreTaggedTypes.scala
  src/main/scala/encry/utils/Utils.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/ObjectsStore.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/EncrySyncInfo.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/history/processors/BlockProcessor.scala
  src/main/scala/encry/view/history/storage/HistoryStorage.scala
  src/main/scala/encry/view/mempool/EncryMempool.scala
  src/main/scala/encry/view/mempool/EncryMempoolReader.scala
  src/main/scala/encry/view/mempool/MempoolReader.scala
  src/main/scala/encry/view/state/DigestState.scala
  src/main/scala/encry/view/state/EncryState.scala
  src/main/scala/encry/view/state/MinimalState.scala
  src/main/scala/encry/view/state/StateReader.scala
  src/main/scala/encry/view/state/UtxoState.scala
  src/main/scala/encry/view/wallet/EncryWallet.scala
  src/main/scala/encry/view/wallet/Vault.scala
  src/test/scala/encry/local/explorer/BlockListenerSpec.scala
  src/test/scala/encry/modifiers/history/block/EncryBlockSerializerTest.scala
  src/test/scala/encry/modifiers/history/block/payload/EncryBlockPayloadSerializerTest.scala
  src/test/scala/encry/utils/EncryGenerator.scala
  src/test/scala/encry/view/wallet/WalletSpec.scala
Labels: done

#176 ec-446: removed column from logs
  src/main/resources/logback.xml
Labels: review required

#163 EC-300 restore blockchain from Postgres
  src/main/resources/Explorer_data_model.sql
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/api/http/routes/TransactionsApiRoute.scala
  src/main/scala/encry/cli/commands/Transfer.scala
  src/main/scala/encry/local/explorer/database/DBService.scala
  src/main/scala/encry/local/explorer/database/QueryRepository.scala
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/modifiers/history/block/header/EncryBlockHeader.scala
  src/main/scala/encry/modifiers/history/block/payload/EncryBlockPayload.scala
  src/main/scala/encry/modifiers/mempool/EncryTransaction.scala
  src/main/scala/encry/modifiers/mempool/Transaction.scala
  src/main/scala/encry/modifiers/mempool/TransactionFactory.scala
  src/main/scala/encry/modifiers/mempool/directive/AssetIssuingDirective.scala
  src/main/scala/encry/modifiers/mempool/directive/DataDirective.scala
  src/main/scala/encry/modifiers/mempool/directive/Directive.scala
  src/main/scala/encry/modifiers/mempool/directive/ScriptedAssetDirective.scala
  src/main/scala/encry/modifiers/mempool/directive/TransferDirective.scala
  src/main/scala/encry/modifiers/serialization/EncrySerializers.scala
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/network/PostgresRestore.scala
  src/main/scala/encry/network/peer/PeerManager.scala
  src/main/scala/encry/settings/EncryAppSettings.scala
  src/main/scala/encry/settings/PostgresSettings.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/mempool/EncryMempool.scala
  src/test/scala/encry/api/http/routes/TransactionsApiRouteSpec.scala
  src/test/scala/encry/local/explorer/BlockListenerSpec.scala
  src/test/scala/encry/modifiers/InstanceFactory.scala
  src/test/scala/encry/modifiers/history/block/payload/EncryBlockPayloadSerializerTest.scala
  src/test/scala/encry/modifiers/mempool/TransactionSerializerTest.scala
  src/test/scala/encry/modifiers/mempool/TransactionSpec.scala
  src/test/scala/encry/utils/EncryGenerator.scala
  src/test/scala/encry/view/mempool/EncryMempoolSpec.scala
  src/test/scala/encry/view/state/UtxoStateSpec.scala
  src/test/scala/encry/view/wallet/WalletSpec.scala
Labels: done

#177 ec-432 use socket as a name of node
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/api/http/routes/InfoApiRoute.scala
  src/main/scala/encry/modifiers/history/block/EncryBlock.scala
  src/main/scala/encry/network/PeerConnectionHandler.scala
  src/main/scala/encry/settings/NetworkSettings.scala
  src/main/scala/encry/stats/StatsSender.scala
Labels: review required

#180 `test-data` directory removed. (ec-459)
  src/test/scala/encry/modifiers/history/block/EncryBlockSerializerTest.scala
  src/test/scala/encry/modifiers/history/block/payload/EncryBlockPayloadSerializerTest.scala
  src/test/scala/encry/modifiers/state/Keys.scala
  src/test/scala/encry/utils/EncryGenerator.scala
  src/test/scala/encry/utils/TestHelper.scala
  src/test/scala/encry/view/state/UtxoStateSpec.scala
  test-data/pki-tx-data-test.json
  test-data/pt-test-data.json
  test-data/seeds
Labels: review required

#183 ec-456 Make everything possible in config optional in order to minimize and unify size of a config
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/local/explorer/database/DBService.scala
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/network/DeliveryManager.scala
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/network/NetworkController.scala
  src/main/scala/encry/network/PostgresRestore.scala
  src/main/scala/encry/network/peer/PeerManager.scala
  src/main/scala/encry/settings/EncryAppSettings.scala
  src/main/scala/encry/settings/NetworkSettings.scala
  src/main/scala/encry/settings/NodeSettings.scala
  src/main/scala/encry/settings/RESTApiSettings.scala
  src/main/scala/encry/stats/KafkaActor.scala
  src/main/scala/encry/stats/StatsSender.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/wallet/AccountManager.scala
Labels: done

#178 EC-450 pg write queries optimization
  src/main/resources/Explorer_data_model.sql
  src/main/resources/application.conf
  src/main/scala/encry/local/explorer/BlockListener.scala
  src/main/scala/encry/local/explorer/database/DBService.scala
  src/main/scala/encry/local/explorer/database/QueryRepository.scala
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/modifiers/history/block/header/EncryBlockHeader.scala
  src/main/scala/encry/modifiers/mempool/Transaction.scala
  src/main/scala/encry/modifiers/mempool/directive/AssetIssuingDirective.scala
  src/main/scala/encry/modifiers/mempool/directive/DataDirective.scala
  src/main/scala/encry/modifiers/mempool/directive/Directive.scala
  src/main/scala/encry/modifiers/mempool/directive/ScriptedAssetDirective.scala
  src/main/scala/encry/modifiers/mempool/directive/TransferDirective.scala
  src/main/scala/encry/network/PostgresRestore.scala
  src/main/scala/encry/settings/PostgresSettings.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/test/scala/encry/local/explorer/BlockListenerSpec.scala
Labels: done

#187 ec-443 api Info should give info about leveldb (write/read) and onlyknownpeers
  src/main/scala/encry/api/http/routes/InfoApiRoute.scala
  src/main/scala/encry/settings/EncryAppSettings.scala
Labels: done

#188 ec-ref
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/api/http/routes/HistoryApiRoute.scala
  src/main/scala/encry/api/http/routes/InfoApiRoute.scala
  src/main/scala/encry/avltree/AuthenticatedTreeOps.scala
  src/main/scala/encry/avltree/BatchAVLProver.scala
  src/main/scala/encry/avltree/VersionedIODBAVLStorage.scala
  src/main/scala/encry/consensus/CandidateBlock.scala
  src/main/scala/encry/consensus/ConsensusScheme.scala
  src/main/scala/encry/consensus/ConsensusSchemeReaders.scala
  src/main/scala/encry/consensus/EquihashPowScheme.scala
  src/main/scala/encry/consensus/PowLinearController.scala
  src/main/scala/encry/local/explorer/BlockListener.scala
  src/main/scala/encry/local/explorer/database/DBService.scala
  src/main/scala/encry/local/explorer/database/QueryRepository.scala
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/modifiers/EncryPersistentModifier.scala
  src/main/scala/encry/modifiers/history/Block.scala
  src/main/scala/encry/modifiers/history/Header.scala
  src/main/scala/encry/modifiers/history/HeaderChain.scala
  src/main/scala/encry/modifiers/history/HistoryModifierSerializer.scala
  src/main/scala/encry/modifiers/history/Payload.scala
  src/main/scala/encry/modifiers/history/block/Block.scala
  src/main/scala/encry/modifiers/history/block/EncryBaseBlock.scala
  src/main/scala/encry/modifiers/history/block/header/EncryBaseBlockHeader.scala
  src/main/scala/encry/modifiers/history/block/header/EncryHeaderChain.scala
  src/main/scala/encry/modifiers/history/block/payload/EncryBaseBlockPayload.scala
  src/main/scala/encry/modifiers/mempool/Transaction.scala
  src/main/scala/encry/modifiers/serialization/EncrySerializers.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/network/PostgresRestore.scala
  src/main/scala/encry/settings/Constants.scala
  src/main/scala/encry/stats/StatsSender.scala
  src/main/scala/encry/validation/ModifierValidation.scala
  src/main/scala/encry/validation/ValidationResult.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/ModifiersCache.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/EncrySyncInfo.scala
  src/main/scala/encry/view/history/processors/BlockDownloadProcessor.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/history/processors/BlockProcessor.scala
  src/main/scala/encry/view/history/processors/payload/BaseBlockPayloadProcessor.scala
  src/main/scala/encry/view/history/processors/payload/BlockPayloadProcessor.scala
  src/main/scala/encry/view/history/processors/payload/EmptyBlockPayloadProcessor.scala
  src/main/scala/encry/view/history/processors/proofs/FullProofProcessor.scala
  src/main/scala/encry/view/state/DigestState.scala
  src/main/scala/encry/view/state/UtxoState.scala
  src/main/scala/encry/view/wallet/EncryWallet.scala
  src/test/scala/encry/local/explorer/BlockListenerSpec.scala
  src/test/scala/encry/modifiers/history/BlockSerializerTest.scala
  src/test/scala/encry/modifiers/history/HeaderSerializerTest.scala
  src/test/scala/encry/modifiers/history/HeaderSpec.scala
  src/test/scala/encry/modifiers/history/PayloadSerializerTest.scala
  src/test/scala/encry/utils/EncryGenerator.scala
  src/test/scala/encry/view/wallet/WalletSpec.scala
Labels: done

#189 EС-479 filling gap between explorer node height and stored in db height
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/api/http/routes/HistoryApiRoute.scala
  src/main/scala/encry/local/explorer/BlockListener.scala
  src/main/scala/encry/local/explorer/database/DBService.scala
  src/main/scala/encry/network/PostgresRestore.scala
  src/main/scala/encry/view/EncryViewReadersHolder.scala
  src/test/scala/encry/local/explorer/BlockListenerSpec.scala
Labels: review required

#193 EC-486 Added possibility to restore from postgres with non-empty state
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/network/PostgresRestore.scala
Labels: review required

#195 ec-refactoring
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/api/http/ApiDirectives.scala
  src/main/scala/encry/api/http/ApiError.scala
  src/main/scala/encry/api/http/ApiRoute.scala
  src/main/scala/encry/api/http/PeersApiRoute.scala
  src/main/scala/encry/api/http/ScorexApiResponse.scala
  src/main/scala/encry/network/DeliveryManager.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/message/MessageHandler.scala
  src/main/scala/encry/network/peer/PeerDatabase.scala
  src/main/scala/encry/network/peer/PeerManager.scala
  src/main/scala/encry/utils/ActorHelper.scala
Labels: work in progress

#190 Ec 474#incorrect full height calculating
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/stats/Zombie.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/history/processors/BlockProcessor.scala
  src/test/scala/encry/utils/EncryGenerator.scala
Labels: review required

#201 Fixed non complete pattern matching
  src/main/scala/encry/api/http/routes/InfoApiRoute.scala
Labels: done

#200 Ec-refactoring
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/network/DeliveryManager.scala
  src/main/scala/encry/utils/NetworkTime.scala
  src/main/scala/encry/view/ObjectsStore.scala
  src/main/scala/encry/view/state/BoxHolder.scala
  src/main/scala/encry/view/state/DigestState.scala
  src/main/scala/encry/view/state/EncryState.scala
  src/main/scala/encry/view/state/StateReader.scala
  src/main/scala/encry/view/state/UtxoState.scala
Labels: work in progress
