Repository EncryFoundation/EncryCore, pull requests merged in 2018-10, with the labels that each got.

#202 ec-487 give actual info about pg and ldb
  src/main/scala/encry/api/http/routes/InfoApiRoute.scala
  src/main/scala/encry/network/PostgresRestore.scala
  src/main/scala/encry/network/peer/PeerManager.scala
Labels: review required

#196 EC-426#Bug with duplicate connections fix
  src/main/scala/encry/network/PeerManager.scala
  src/test/scala/encry/utils/EncryGenerator.scala
Labels: review required

#204 Ec 494#incorrect headers height
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/local/miner/Worker.scala
  src/main/scala/encry/network/DeliveryManager.scala
  src/main/scala/encry/network/NodeViewSynchronizer.scala
  src/main/scala/encry/network/SyncTracker.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/ModifiersCache.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/history/processors/BlockProcessor.scala
  src/main/scala/encry/view/mempool/EncryMempool.scala
Labels: review required

#211 ec-mnemonic
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/avltree/VersionedIODBAVLStorage.scala
  src/main/scala/encry/network/ModifiersHolder.scala
Labels: work in progress

#212 EC-505 network layer fixing
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/network/DeliveryManager.scala
  src/main/scala/encry/network/NodeViewSynchronizer.scala
  src/main/scala/encry/network/PeerManager.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/ModifiersCache.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/history/processors/BlockProcessor.scala
  src/main/scala/encry/view/history/processors/payload/BlockPayloadProcessor.scala
  src/main/scala/encry/view/wallet/AccountManager.scala
Labels: work in progress

#220 ec - fixed dataTxs
  src/main/scala/encry/modifiers/mempool/Transaction.scala
Labels: review required

#222 EC-512
  src/main/scala/encry/local/explorer/database/QueryRepository.scala
Labels: review required

#225 ec-fix
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/api/http/routes/HistoryApiRoute.scala
  src/main/scala/encry/api/http/routes/InfoApiRoute.scala
  src/main/scala/encry/api/http/routes/StateInfoApiRoute.scala
  src/main/scala/encry/api/http/routes/TransactionsApiRoute.scala
  src/main/scala/encry/api/http/routes/WalletInfoApiRoute.scala
  src/main/scala/encry/cli/commands/CreateKey.scala
  src/main/scala/encry/cli/commands/GetBalance.scala
  src/main/scala/encry/cli/commands/PrintAddresses.scala
  src/main/scala/encry/cli/commands/PrintPrivKeys.scala
  src/main/scala/encry/cli/commands/PrintPubKeys.scala
  src/main/scala/encry/cli/commands/Transfer.scala
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/modifiers/ModifierWithDigest.scala
  src/main/scala/encry/modifiers/state/StateModifierDeserializer.scala
  src/main/scala/encry/modifiers/state/box/Box.scala
  src/main/scala/encry/modifiers/state/box/EncryBox.scala
  src/main/scala/encry/network/DeliveryManager.scala
  src/main/scala/encry/network/NodeViewSynchronizer.scala
  src/main/scala/encry/settings/NodeSettings.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/ModifiersCache.scala
  src/main/scala/encry/view/ReadersHolder.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/mempool/EncryMempoolReader.scala
  src/main/scala/encry/view/mempool/MemoryPool.scala
  src/main/scala/encry/view/mempool/Mempool.scala
  src/main/scala/encry/view/mempool/MempoolReader.scala
  src/test/scala/encry/view/mempool/MempoolSpec.scala
Labels: work in progress

#228 EC-509
  src/main/scala/encry/local/explorer/database/DBService.scala
Labels: review required

#241 Added different installation guides
  README.md
  src/main/scala/encry/cli/commands/Help.scala
Labels: review required

#243 ec-yaf
  src/main/resources/application.conf
  src/main/resources/logback.xml
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/modifiers/history/Header.scala
  src/main/scala/encry/network/DeliveryManager.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/ModifiersCache.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/history/processors/payload/BlockPayloadProcessor.scala
Labels: masterpiece, work in progress
