Repository EncryFoundation/EncryCore, pull requests merged in 2018-07, with the labels that each got.

#84 Incorrect start of transaction generator fixed
  src/main/scala/encry/view/wallet/storage/WalletStorage.scala
Labels: bug, review required

#76 Ec-238 PeerDatabase and logic about peer refactoring
  src/main/scala/encry/network/PeerConnectionHandler.scala
  src/main/scala/encry/network/peer/PeerDatabase.scala
  src/main/scala/encry/network/peer/PeerManager.scala
Labels: done

#87 ec-251 Remove type aliases from EncryApp
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/local/miner/EncryMiner.scala
  src/main/scala/encry/network/NetworkController.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
Labels: review required

#86 Logging utils and format (Ec 232)
  .gitignore
  src/main/resources/logback.xml
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/api/http/routes/HistoryApiRoute.scala
  src/main/scala/encry/cli/ConsolePromptListener.scala
  src/main/scala/encry/consensus/EquihashPowScheme.scala
  src/main/scala/encry/crypto/equihash/Equihash.scala
  src/main/scala/encry/local/EncryLocalInterface.scala
  src/main/scala/encry/local/TransactionGenerator.scala
  src/main/scala/encry/local/miner/EncryMiner.scala
  src/main/scala/encry/local/miner/EncryMiningWorker.scala
  src/main/scala/encry/modifiers/history/block/EncryBaseBlock.scala
  src/main/scala/encry/network/DeliveryTracker.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/NetworkController.scala
  src/main/scala/encry/network/PeerConnectionHandler.scala
  src/main/scala/encry/network/PeerSynchronizer.scala
  src/main/scala/encry/network/SyncTracker.scala
  src/main/scala/encry/network/UPnP.scala
  src/main/scala/encry/network/peer/PeerManager.scala
  src/main/scala/encry/settings/EncryAppSettings.scala
  src/main/scala/encry/stats/StatsSender.scala
  src/main/scala/encry/storage/EncryBaseStorage.scala
  src/main/scala/encry/utils/EncryLogging.scala
  src/main/scala/encry/utils/ExtUtils.scala
  src/main/scala/encry/utils/NetworkTime.scala
  src/main/scala/encry/utils/ScorexLogging.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/EncryViewReadersHolder.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/history/processors/BlockProcessor.scala
  src/main/scala/encry/view/history/processors/DownloadProcessor.scala
  src/main/scala/encry/view/history/storage/HistoryStorage.scala
  src/main/scala/encry/view/mempool/EncryMempool.scala
  src/main/scala/encry/view/state/DigestState.scala
  src/main/scala/encry/view/state/EncryState.scala
  src/main/scala/encry/view/state/UtxoState.scala
  src/main/scala/encry/view/state/UtxoStateReader.scala
  src/main/scala/encry/view/wallet/EncryWallet.scala
  src/main/scala/encry/view/wallet/keys/KeyManager.scala
Labels: review required

#88 Ec-envh
  src/main/resources/comment.txt
  src/main/scala/encry/view/EncryNodeViewHolder.scala
Labels: done

#85 Info about all routes in current version of node (Ec-219)
  docs/design/NodeRoutes.md
  src/main/scala/encry/api/http/UtilsApiRoute.scala
  src/main/scala/encry/api/http/routes/HistoryApiRoute.scala
  src/main/scala/encry/api/http/routes/TransactionsApiRoute.scala
Labels: done, masterpiece

#71 Incorrec order of modifiers download#ec 228
  docs/design/CoreComponentsSpec.md
  docs/design/ModelsSpec.md
  docs/design/ProtocolSpec.md
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/api/http/routes/HistoryApiRoute.scala
  src/main/scala/encry/api/http/routes/InfoApiRoute.scala
  src/main/scala/encry/cli/ConsolePromptListener.scala
  src/main/scala/encry/cli/commands/Transfer.scala
  src/main/scala/encry/consensus/EquihashPowScheme.scala
  src/main/scala/encry/local/EncryLocalInterface.scala
  src/main/scala/encry/local/TransactionGenerator.scala
  src/main/scala/encry/local/miner/EncryMiner.scala
  src/main/scala/encry/local/miner/EncryMiningWorker.scala
  src/main/scala/encry/modifiers/history/block/EncryBaseBlock.scala
  src/main/scala/encry/modifiers/mempool/directive/ScriptedAssetDirective.scala
  src/main/scala/encry/network/DeliveryTracker.scala
  src/main/scala/encry/network/EncryDeliveryManager.scala
  src/main/scala/encry/network/EncryDeliveryTracker.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/NetworkController.scala
  src/main/scala/encry/network/PeerConnectionHandler.scala
  src/main/scala/encry/network/PeerSynchronizer.scala
  src/main/scala/encry/network/SyncTracker.scala
  src/main/scala/encry/network/UPnP.scala
  src/main/scala/encry/network/message/BasicMessagesRepo.scala
  src/main/scala/encry/network/peer/PeerManager.scala
  src/main/scala/encry/settings/EncryAppSettings.scala
  src/main/scala/encry/settings/NetworkSettings.scala
  src/main/scala/encry/stats/StatsSender.scala
  src/main/scala/encry/storage/EncryBaseStorage.scala
  src/main/scala/encry/utils/Logging.scala
  src/main/scala/encry/utils/NetworkTime.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/EncryViewReadersHolder.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/history/processors/BlockProcessor.scala
  src/main/scala/encry/view/history/processors/DownloadProcessor.scala
  src/main/scala/encry/view/mempool/EncryMempool.scala
  src/main/scala/encry/view/state/DigestState.scala
  src/main/scala/encry/view/state/EncryState.scala
  src/main/scala/encry/view/state/UtxoState.scala
  src/main/scala/encry/view/state/UtxoStateReader.scala
  src/main/scala/encry/view/wallet/EncryWallet.scala
  src/main/scala/encry/view/wallet/keys/KeyManager.scala
  src/main/scala/scorex/crypto/authds/avltree/batch/VersionedIODBAVLStorage.scala
  src/test/scala/encry/consensus/PowLinearControllerSpec.scala
  src/test/scala/encry/modifiers/InstanceFactory.scala
  src/test/scala/encry/utils/EncryGenerator.scala
Labels: done

#91 fix
  src/main/resources/application.conf
Labels: review required

#92 ec - dispatcher for peerConHandlers
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/network/NetworkController.scala
Labels: done

#96 Bugfix (Ec-232)
  src/main/scala/encry/utils/Logging.scala
Labels: done

#95 Http server exc handling (#247)
  build.sbt
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/api/http/routes/InfoApiRoute.scala
  src/main/scala/encry/settings/RESTApiSettings.scala
Labels: done

#94 Http server startup handling from config.
  src/main/scala/encry/EncryApp.scala
Labels: done

#90 Ec-255 Message Handling refactoring
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/consensus/History.scala
  src/main/scala/encry/network/EncryDeliveryManager.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/NetworkController.scala
  src/main/scala/encry/network/PeerConnectionHandler.scala
  src/main/scala/encry/network/PeerSynchronizer.scala
  src/main/scala/encry/network/SendingStrategy.scala
  src/main/scala/encry/network/message/Message.scala
  src/main/scala/encry/network/peer/PeerManager.scala
Labels: done

#66 Ec-218 persistent actor
  build.sbt
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/network/EncryDeliveryManager.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/network/NetworkController.scala
  src/main/scala/encry/network/PeerConnectionHandler.scala
  src/main/scala/encry/network/PeerSynchronizer.scala
  src/main/scala/encry/network/SendingStrategy.scala
  src/main/scala/encry/network/peer/PeerManager.scala
  src/main/scala/encry/stats/StatsSender.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/processors/BlockProcessor.scala
  src/main/scala/encry/view/history/processors/payload/BlockPayloadProcessor.scala
  src/test/scala/encry/network/ModifiersHolderTest.scala
Labels: review required

#99 Ec 267 Refactoring- history
  src/main/scala/encry/consensus/History.scala
  src/main/scala/encry/consensus/HistoryReader.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/peer/PeerManager.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/history/processors/DownloadProcessor.scala
Labels: done

#102 new stats added#EC-263
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/stats/StatsSender.scala
Labels: done

#101 ec-271: Make persistence on ModsHolder + optional instanciating
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/settings/NodeSettings.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
Labels: review required

#100 LosingState#EC-261
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/settings/EncryAppSettings.scala
  src/main/scala/encry/settings/LevelDbSettings.scala
  src/main/scala/encry/settings/NodeSettings.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/state/UtxoState.scala
Labels: done

#106 Ec-setts
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/network/PeerSynchronizer.scala
  src/main/scala/encry/settings/Constants.scala
  src/main/scala/encry/settings/EncryAppSettings.scala
  src/main/scala/encry/settings/NetworkSettings.scala
  src/main/scala/encry/settings/NodeSettings.scala
Labels: done

#103 Mempool sync#ec 278
  src/main/scala/encry/cli/commands/StartMine.scala
  src/main/scala/encry/cli/commands/StopMine.scala
  src/main/scala/encry/network/DeliveryTracker.scala
  src/main/scala/encry/network/EncryDeliveryManager.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/history/EncryHistory.scala
Labels: review required

#93 FileSystemHistory storage removed, iodb is used instead. (EC-257)
  src/main/scala/encry/api/http/routes/TransactionsApiRoute.scala
  src/main/scala/encry/cli/ConsolePromptListener.scala
  src/main/scala/encry/local/miner/EncryMiner.scala
  src/main/scala/encry/local/miner/EncryMiningWorker.scala
  src/main/scala/encry/modifiers/history/block/EncryBaseBlock.scala
  src/main/scala/encry/modifiers/history/block/header/EncryBlockHeader.scala
  src/main/scala/encry/modifiers/history/block/payload/EncryBlockPayload.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/stats/StatsSender.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/ModifiersCache.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/processors/BlockProcessor.scala
  src/main/scala/encry/view/history/processors/payload/BlockPayloadProcessor.scala
  src/main/scala/encry/view/history/processors/proofs/FullProofProcessor.scala
  src/main/scala/encry/view/history/storage/FileHistoryObjectsStore.scala
  src/main/scala/encry/view/history/storage/HistoryStorage.scala
  src/main/scala/encry/view/state/UtxoState.scala
  src/test/scala/scorex/crypto/authds/avltree/batch/benchmark/BatchingBenchmark.scala
  src/test/scala/scorex/crypto/authds/avltree/batch/benchmark/IODBBenchmark.scala
Labels: work in progress

#109 ec-nvh-dispatcher
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/network/EncryDeliveryManager.scala
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/utils/Zombie.scala
Labels: done

#107 Add logging of incoming messages
  src/main/scala/encry/network/EncryDeliveryManager.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/network/NetworkController.scala
  src/main/scala/encry/network/PeerConnectionHandler.scala
  src/main/scala/encry/network/PeerSynchronizer.scala
  src/main/scala/encry/network/peer/PeerManager.scala
  startup.sh
Labels: done

#110 Ec 294#peer handler death
  src/main/scala/encry/network/EncryDeliveryManager.scala
  src/main/scala/encry/network/PeerConnectionHandler.scala
  src/main/scala/encry/network/SyncTracker.scala
Labels: work in progress

#112 Ec 294#2#peer connection handler death
  src/main/scala/encry/network/PeerConnectionHandler.scala
Labels: masterpiece

#113 persistentProver fix
  src/main/scala/encry/view/state/UtxoState.scala
  src/main/scala/encry/view/state/UtxoStateReader.scala
  src/test/scala/encry/utils/EncryGenerator.scala
  src/test/scala/encry/view/state/UtxoStateSpec.scala
Labels: done

#114 Ec-252Transactions refactoring
  src/main/scala/encry/consensus/CandidateBlock.scala
  src/main/scala/encry/consensus/ConsensusScheme.scala
  src/main/scala/encry/consensus/EquihashPowScheme.scala
  src/main/scala/encry/local/miner/EncryMiner.scala
  src/main/scala/encry/modifiers/NodeViewModifier.scala
  src/main/scala/encry/modifiers/history/block/EncryBaseBlock.scala
  src/main/scala/encry/modifiers/history/block/EncryBlock.scala
  src/main/scala/encry/modifiers/history/block/payload/EncryBaseBlockPayload.scala
  src/main/scala/encry/modifiers/history/block/payload/EncryBlockPayload.scala
  src/main/scala/encry/modifiers/mempool/BaseTransaction.scala
  src/main/scala/encry/modifiers/mempool/EncryTransaction.scala
  src/main/scala/encry/modifiers/mempool/ModifierWithSizeLimit.scala
  src/main/scala/encry/modifiers/mempool/Transaction.scala
  src/main/scala/encry/modifiers/state/box/Context.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/settings/Algos.scala
  src/main/scala/encry/utils/Utils.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/mempool/EncryMempool.scala
  src/main/scala/encry/view/mempool/EncryMempoolReader.scala
  src/main/scala/encry/view/mempool/MemoryPool.scala
  src/main/scala/encry/view/mempool/MempoolReader.scala
  src/main/scala/encry/view/state/DigestState.scala
  src/main/scala/encry/view/state/EncryState.scala
  src/main/scala/encry/view/state/MinimalState.scala
  src/main/scala/encry/view/state/UtxoState.scala
  src/main/scala/encry/view/wallet/EncryWallet.scala
  src/main/scala/encry/view/wallet/Vault.scala
  src/test/scala/encry/modifiers/InstanceFactory.scala
  src/test/scala/encry/modifiers/mempool/EncryTransactionSerializerTest.scala
  src/test/scala/encry/modifiers/state/BoxIdGenerationTest.scala
  src/test/scala/encry/utils/FileHelper.scala
Labels: done

#116 Modifiers validation fixed.
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/history/processors/BlockProcessor.scala
Labels: done

#118 EC-299#Transaction generator
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/local/TransactionGenerator.scala
  src/main/scala/encry/local/miner/EncryMiner.scala
  src/main/scala/encry/settings/TestingSettings.scala
  src/main/scala/encry/stats/StatsSender.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
Labels: done

#120 Colored coin issuing protocol improved. (EC-319)
  src/main/scala/encry/modifiers/mempool/directive/AssetIssuingDirective.scala
  src/main/scala/encry/modifiers/state/StateModifierDeserializer.scala
  src/main/scala/encry/modifiers/state/box/AssetBox.scala
  src/main/scala/encry/modifiers/state/box/AssetCreationBox.scala
  src/main/scala/encry/modifiers/state/box/EncryBaseBox.scala
  src/main/scala/encry/modifiers/state/box/TokenIssuingBox.scala
  src/main/scala/encry/settings/Constants.scala
  src/main/scala/encry/utils/BalanceCalculator.scala
  src/main/scala/encry/utils/ByteStr.scala
  src/main/scala/encry/view/state/UtxoState.scala
  src/main/scala/encry/view/wallet/EncryWallet.scala
  src/main/scala/encry/view/wallet/storage/WalletStorage.scala
  src/test/scala/encry/modifiers/InstanceFactory.scala
  src/test/scala/encry/modifiers/state/AssetCreationBoxSerializerTest.scala
Labels: review required

#125 Orphaned header processing fix. (EC-337)
  src/main/scala/encry/modifiers/history/block/header/EncryBlockHeader.scala
Labels: review required

#126 fix
  src/main/scala/encry/EncryApp.scala
Labels: review required

#127 privKey
  src/main/scala/encry/cli/ConsolePromptListener.scala
Labels: review required

#117 EC-310#Enable sending sync message after applying all payloads in Modifiers Cache
  src/main/scala/encry/local/miner/EncryMiner.scala
  src/main/scala/encry/network/EncryDeliveryManager.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/NetworkController.scala
  src/main/scala/encry/network/PeerConnectionHandler.scala
  src/main/scala/encry/network/SyncTracker.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/ModifiersCache.scala
Labels: done

#128 EC-328 Switched serializers from default to custom
  src/main/resources/application.conf
  src/main/scala/encry/modifiers/history/block/header/EncryBlockHeader.scala
  src/main/scala/encry/modifiers/serialization/EncrySerializers.scala
Labels: done
