Repository EncryFoundation/EncryCore, pull requests merged in 2018-08, with the labels that each got.

#130 ec-leveldb
  src/main/resources/application.conf
  src/main/scala/encry/network/ModifiersHolder.scala
Labels: done

#129 EC-343#IncorrectWalletRestarting
  src/main/scala/encry/view/wallet/keys/KeyManager.scala
Labels: done

#119 Serializing structures and messages spec
  docs/design/SerializationFormat.md
Labels: done, postponed

#122 EC-339#Constants/MagicNumbers to settings
  src/main/resources/application.conf
  src/main/scala/encry/modifiers/history/block/EncryBlock.scala
  src/main/scala/encry/settings/Constants.scala
  src/main/scala/encry/settings/NetworkSettings.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/EncrySyncInfo.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
Labels: review required

#135 New address formats (EC-350)
  src/main/scala/encry/account/Account.scala
  src/main/scala/encry/account/package.scala
  src/main/scala/encry/api/http/routes/EncryBaseApiRoute.scala
  src/main/scala/encry/cli/ConsolePromptListener.scala
  src/main/scala/encry/cli/commands/PrintAddresses.scala
  src/main/scala/encry/cli/commands/Transfer.scala
  src/main/scala/encry/crypto/PublicKey25519.scala
  src/main/scala/encry/crypto/encoding/Base58Check.scala
  src/main/scala/encry/encry.scala
  src/main/scala/encry/local/TransactionGenerator.scala
  src/main/scala/encry/local/miner/EncryMiner.scala
  src/main/scala/encry/modifiers/mempool/EncryAddress.scala
  src/main/scala/encry/modifiers/mempool/TransactionFactory.scala
  src/main/scala/encry/modifiers/mempool/directive/TransferDirective.scala
  src/main/scala/encry/modifiers/mempool/regcontract/RegularContract.scala
  src/main/scala/encry/modifiers/state/box/EncryProposition.scala
  src/main/scala/encry/view/wallet/EncryWallet.scala
  src/test/scala/encry/modifiers/InstanceFactory.scala
  src/test/scala/encry/modifiers/history/block/EncryBlockSerializerTest.scala
  src/test/scala/encry/modifiers/history/block/payload/EncryBlockPayloadSerializerTest.scala
  src/test/scala/encry/modifiers/mempool/EncryAddressSpec.scala
  src/test/scala/encry/modifiers/state/Keys.scala
  src/test/scala/encry/utils/EncryGenerator.scala
  src/test/scala/encry/utils/TestHelper.scala
  src/test/scala/encry/view/state/UtxoStateSpec.scala
  src/test/scala/encry/view/wallet/WalletSpec.scala
Labels: review required

#97 Proper miner startup handling + miner status displaying fix. (EC-236)
  src/main/scala/encry/local/miner/EncryMiner.scala
Labels: review required

#137 ec-348: refactoring
  build.sbt
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/api/http/routes/HistoryApiRoute.scala
  src/main/scala/encry/api/http/routes/InfoApiRoute.scala
  src/main/scala/encry/cli/commands/StartMine.scala
  src/main/scala/encry/cli/commands/StopMine.scala
  src/main/scala/encry/local/miner/EncryMiningWorker.scala
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/network/DeliveryManager.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/NetworkController.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
Labels: work in progress

#141 EC-301 blockchain recovery from levelDB
  src/main/resources/application.conf
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/network/peer/PeerManager.scala
  src/main/scala/encry/settings/LevelDbSettings.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/ModifiersCache.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
Labels: done

#139 Account backup from seed, encryption. (EC-358)
  src/main/resources/application.conf
  src/main/scala/encry/cli/ConsolePromptListener.scala
  src/main/scala/encry/cli/commands/CreateKey.scala
  src/main/scala/encry/cli/commands/InitKeyStorage.scala
  src/main/scala/encry/cli/commands/PrintAddresses.scala
  src/main/scala/encry/cli/commands/PrintPrivKeys.scala
  src/main/scala/encry/cli/commands/PrintPubKeys.scala
  src/main/scala/encry/cli/commands/Transfer.scala
  src/main/scala/encry/crypto/encryption/AES.scala
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/settings/EncryAppSettings.scala
  src/main/scala/encry/settings/KeyManagerSettings.scala
  src/main/scala/encry/settings/NodeSettings.scala
  src/main/scala/encry/settings/WalletSettings.scala
  src/main/scala/encry/storage/EncryStorage.scala
  src/main/scala/encry/utils/Mnemonic.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/NodeViewComponent.scala
  src/main/scala/encry/view/history/storage/HistoryStorage.scala
  src/main/scala/encry/view/mempool/MempoolReader.scala
  src/main/scala/encry/view/state/StateReader.scala
  src/main/scala/encry/view/state/UtxoState.scala
  src/main/scala/encry/view/wallet/AccountManager.scala
  src/main/scala/encry/view/wallet/EncryWallet.scala
  src/main/scala/encry/view/wallet/Vault.scala
  src/main/scala/encry/view/wallet/WalletStorage.scala
  src/main/scala/encry/view/wallet/keys/KeyManager.scala
  src/test/scala/encry/crypto/encryption/AESSpec.scala
  src/test/scala/encry/view/wallet/WalletSpec.scala
  src/test/scala/encry/view/wallet/storage/WalletStorageSpec.scala
Labels: done

#146 EC-352 Core - if wallet balance 0 it should be 0 not <empty>
  src/main/scala/encry/cli/commands/GetBalance.scala
  src/main/scala/encry/network/ModifiersHolder.scala
Labels: done

#143 EC-353 Miner and MiningWorker logic refactoring
  src/main/resources/application.conf
  src/main/scala/encry/local/miner/EncryMiningWorker.scala
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/utils/Zombie.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
Labels: review required

#150 Non-full blocks issue fix (ec-381)
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/network/DeliveryManager.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/history/processors/BlockProcessor.scala
Labels: done

#154 ec-fix
  src/main/scala/encry/utils/Mnemonic.scala
Labels: review required

#153 ec-kafka
  build.sbt
  src/main/resources/application.conf
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/settings/EncryAppSettings.scala
  src/main/scala/encry/settings/KafkaSettings.scala
  src/main/scala/encry/settings/NodeSettings.scala
  src/main/scala/encry/stats/KafkaActor.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
Labels: review required

#155 EncryWallet fixed. (ec-400)
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/view/wallet/EncryWallet.scala
  src/main/scala/encry/view/wallet/WalletStorage.scala
Labels: done

#162 Connected peers displaying fix. (ec-411)
  src/main/scala/encry/api/http/PeersApiRoute.scala
  src/main/scala/encry/api/http/routes/InfoApiRoute.scala
  src/main/scala/encry/network/peer/PeerManager.scala
Labels: done

#166 Wallet api route implementation. (ec-419)
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/api/http/routes/WalletInfoApiRoute.scala
Labels: review required

#160 ec-397 Core - Make switching mode for logging: no logs / logs into file / logs to Kafka
  src/main/resources/application.conf
  src/main/resources/logback.xml
  src/main/scala/encry/EncryApp.scala
  src/main/scala/encry/api/http/routes/HistoryApiRoute.scala
  src/main/scala/encry/avltree/BatchAVLProver.scala
  src/main/scala/encry/avltree/VersionedIODBAVLStorage.scala
  src/main/scala/encry/cli/ConsolePromptListener.scala
  src/main/scala/encry/consensus/EquihashPowScheme.scala
  src/main/scala/encry/crypto/equihash/Equihash.scala
  src/main/scala/encry/local/TransactionGenerator.scala
  src/main/scala/encry/local/explorer/BlockListener.scala
  src/main/scala/encry/local/explorer/database/DBService.scala
  src/main/scala/encry/local/miner/EncryMiningWorker.scala
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/modifiers/history/block/EncryBaseBlock.scala
  src/main/scala/encry/modifiers/serialization/EncrySerializers.scala
  src/main/scala/encry/network/DeliveryManager.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/network/NetworkController.scala
  src/main/scala/encry/network/PeerConnectionHandler.scala
  src/main/scala/encry/network/PeerSynchronizer.scala
  src/main/scala/encry/network/SyncTracker.scala
  src/main/scala/encry/network/peer/PeerManager.scala
  src/main/scala/encry/settings/EncryAppSettings.scala
  src/main/scala/encry/settings/NodeSettings.scala
  src/main/scala/encry/stats/KafkaActor.scala
  src/main/scala/encry/stats/LoggingActor.scala
  src/main/scala/encry/stats/StatsSender.scala
  src/main/scala/encry/storage/EncryStorage.scala
  src/main/scala/encry/utils/ExtUtils.scala
  src/main/scala/encry/utils/Logging.scala
  src/main/scala/encry/utils/NetworkTime.scala
  src/main/scala/encry/utils/Zombie.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/EncryViewReadersHolder.scala
  src/main/scala/encry/view/ModifiersCache.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/history/processors/BlockProcessor.scala
  src/main/scala/encry/view/history/storage/HistoryStorage.scala
  src/main/scala/encry/view/mempool/EncryMempool.scala
  src/main/scala/encry/view/state/DigestState.scala
  src/main/scala/encry/view/state/EncryState.scala
  src/main/scala/encry/view/state/UtxoState.scala
  src/main/scala/encry/view/state/UtxoStateReader.scala
  src/main/scala/encry/view/wallet/AccountManager.scala
  src/main/scala/encry/view/wallet/EncryWallet.scala
  src/test/scala/encry/avltree/helpers/TestHelper.scala
Labels: done

#161 Transaction validation rules (stateless) improved. (ec-410)
  src/main/scala/encry/local/TransactionGenerator.scala
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/modifiers/mempool/EncryTransaction.scala
  src/main/scala/encry/modifiers/mempool/Transaction.scala
  src/main/scala/encry/settings/Constants.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/mempool/EncryMempool.scala
  src/main/scala/encry/view/wallet/WalletStorage.scala
  src/test/scala/encry/modifiers/mempool/EncryTransactionSpec.scala
Labels: done

#168 EC-266 Removed package object
  src/main/scala/encry/CoreTaggedTypes.scala
  src/main/scala/encry/api/http/routes/EncryBaseApiRoute.scala
  src/main/scala/encry/api/http/routes/HistoryApiRoute.scala
  src/main/scala/encry/consensus/ConsensusScheme.scala
  src/main/scala/encry/consensus/EquihashPowScheme.scala
  src/main/scala/encry/consensus/History.scala
  src/main/scala/encry/encry.scala
  src/main/scala/encry/local/explorer/BlockListener.scala
  src/main/scala/encry/local/explorer/database/DBService.scala
  src/main/scala/encry/local/explorer/database/QueryRepository.scala
  src/main/scala/encry/modifiers/EncryPersistentModifier.scala
  src/main/scala/encry/modifiers/ModifierWithDigest.scala
  src/main/scala/encry/modifiers/NodeViewModifier.scala
  src/main/scala/encry/modifiers/history/ADProofs.scala
  src/main/scala/encry/modifiers/history/block/EncryBlock.scala
  src/main/scala/encry/modifiers/history/block/header/EncryBaseBlockHeader.scala
  src/main/scala/encry/modifiers/history/block/header/EncryBlockHeader.scala
  src/main/scala/encry/modifiers/history/block/payload/EncryBaseBlockPayload.scala
  src/main/scala/encry/modifiers/history/block/payload/EncryBlockPayload.scala
  src/main/scala/encry/modifiers/mempool/EncryTransaction.scala
  src/main/scala/encry/modifiers/mempool/Transaction.scala
  src/main/scala/encry/network/DeliveryManager.scala
  src/main/scala/encry/network/EncryNodeViewSynchronizer.scala
  src/main/scala/encry/network/ModifiersHolder.scala
  src/main/scala/encry/network/message/BasicMessagesRepo.scala
  src/main/scala/encry/stats/StatsSender.scala
  src/main/scala/encry/storage/EncryStorage.scala
  src/main/scala/encry/utils/Utils.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
  src/main/scala/encry/view/ObjectsStore.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/EncrySyncInfo.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/history/processors/BlockProcessor.scala
  src/main/scala/encry/view/history/storage/HistoryStorage.scala
  src/main/scala/encry/view/mempool/EncryMempool.scala
  src/main/scala/encry/view/mempool/EncryMempoolReader.scala
  src/main/scala/encry/view/mempool/MempoolReader.scala
  src/main/scala/encry/view/state/DigestState.scala
  src/main/scala/encry/view/state/EncryState.scala
  src/main/scala/encry/view/state/MinimalState.scala
  src/main/scala/encry/view/state/StateReader.scala
  src/main/scala/encry/view/state/UtxoState.scala
  src/main/scala/encry/view/wallet/EncryWallet.scala
  src/main/scala/encry/view/wallet/Vault.scala
  src/test/scala/encry/local/explorer/BlockListenerSpec.scala
  src/test/scala/encry/modifiers/history/block/EncryBlockSerializerTest.scala
  src/test/scala/encry/modifiers/history/block/payload/EncryBlockPayloadSerializerTest.scala
  src/test/scala/encry/utils/EncryGenerator.scala
  src/test/scala/encry/view/wallet/WalletSpec.scala
Labels: done

#171 EC-428 Removed consensus and history package objects
  src/main/scala/encry/consensus/CandidateBlock.scala
  src/main/scala/encry/consensus/ConsensusScheme.scala
  src/main/scala/encry/consensus/ConsensusTaggedTypes.scala
  src/main/scala/encry/consensus/DifficultySerializer.scala
  src/main/scala/encry/consensus/EncrySupplyController.scala
  src/main/scala/encry/consensus/EquihashPowScheme.scala
  src/main/scala/encry/consensus/PowLinearController.scala
  src/main/scala/encry/local/miner/Miner.scala
  src/main/scala/encry/modifiers/history/block/header/EncryBlockHeader.scala
  src/main/scala/encry/modifiers/mempool/TransactionFactory.scala
  src/main/scala/encry/modifiers/state/box/EncryProposition.scala
  src/main/scala/encry/settings/Constants.scala
  src/main/scala/encry/stats/StatsSender.scala
  src/main/scala/encry/view/history/EncryHistory.scala
  src/main/scala/encry/view/history/EncryHistoryReader.scala
  src/main/scala/encry/view/history/History.scala
  src/main/scala/encry/view/history/processors/BlockHeaderProcessor.scala
  src/main/scala/encry/view/state/EncryStateView.scala
  src/main/scala/encry/view/state/UtxoState.scala
  src/main/scala/encry/view/state/UtxoStateReader.scala
  src/test/scala/encry/consensus/PowLinearControllerSpec.scala
  src/test/scala/encry/consensus/emission/EncrySupplyControllerTest.scala
  src/test/scala/encry/modifiers/InstanceFactory.scala
  src/test/scala/encry/modifiers/history/block/payload/EncryBlockPayloadSerializerTest.scala
  src/test/scala/encry/modifiers/state/box/proposition/StateContext.scala
  src/test/scala/encry/view/state/UtxoStateSpec.scala
Labels: review required

#170 ec-423 make logging to file per day and deleting old files
  src/main/resources/logback.xml
Labels: done

#173 Ec-427 Core - create metric full height + headers height
  src/main/scala/encry/stats/StatsSender.scala
  src/main/scala/encry/view/EncryNodeViewHolder.scala
Labels: done
